import { ArrowLeft, ArrowRight, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { Link } from "react-router-dom";

import { LeadFunnel } from "@/pages/Home";

export default function Contact() {
  return <div className="min-h-screen bg-[#fafafa] text-[#1a1a1a]" data-testid="contact-page">
    <header className="border-b border-[#e5e1dd] bg-white" data-testid="contact-header"><div className="mx-auto flex h-[72px] max-w-[1240px] items-center justify-between px-4 sm:px-8 lg:px-12"><Link to="/" className="flex items-center gap-3" data-testid="contact-back-home-link"><span className="grid size-9 place-items-center bg-[#1a1a1a] text-white"><span className="font-heading text-xl">A</span></span><span className="text-sm font-bold tracking-[0.08em]">AANGAN <span className="font-normal text-[#a38068]">BUILDWORKS</span></span></Link><Link to="/" className="flex items-center gap-2 text-xs font-bold text-[#666] hover:text-[#a38068]" data-testid="contact-return-link"><ArrowLeft size={15} /> Back to home</Link></div></header>
    <main><section className="bg-[#1f2423] px-4 py-20 text-white sm:px-8 lg:px-12 lg:py-28" data-testid="contact-hero-section"><div className="mx-auto max-w-[1240px]"><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.22em] text-[#d0ad92]" data-testid="contact-eyebrow">Start with your land</p><h1 className="max-w-3xl text-5xl font-medium leading-[0.98] text-white sm:text-7xl" data-testid="contact-title">Let’s start with your land.</h1><p className="mt-6 max-w-lg text-base leading-7 text-white/65" data-testid="contact-subtitle">Tell us about the plot and home you’re planning. A home consultant will help you understand the next step.</p></div></section><section className="mx-auto grid max-w-[1240px] gap-12 px-4 py-16 sm:px-8 lg:grid-cols-[0.7fr_1.3fr] lg:px-12 lg:py-24" data-testid="contact-content"><div><p className="text-[11px] font-bold uppercase tracking-[0.22em] text-[#a38068]" data-testid="contact-details-eyebrow">Aangan Buildworks</p><h2 className="mt-4 text-3xl font-medium" data-testid="contact-details-title">A considered conversation, before a construction promise.</h2><p className="mt-5 text-sm leading-7 text-[#666]" data-testid="contact-details-copy">The contact details below are placeholders for this preview and can be replaced with the company’s verified details.</p><div className="mt-10 grid gap-5 text-sm"><a href="tel:+919999999999" className="flex items-center gap-3 hover:text-[#a38068]" data-testid="contact-phone-link"><Phone size={17} className="text-[#a38068]" /> +91 99999 99999</a><a href="https://wa.me/919999999999" target="_blank" rel="noreferrer" className="flex items-center gap-3 hover:text-[#a38068]" data-testid="contact-whatsapp-link"><MessageCircle size={17} className="text-[#a38068]" /> Discuss your home on WhatsApp</a><a href="mailto:hello@aanganbuildworks.example" className="flex items-center gap-3 hover:text-[#a38068]" data-testid="contact-email-link"><Mail size={17} className="text-[#a38068]" /> hello@aanganbuildworks.example</a><span className="flex items-center gap-3 text-[#666]" data-testid="contact-location"><MapPin size={17} className="text-[#a38068]" /> Bihar, India · service availability confirmed by brief</span></div></div><LeadFunnel /></section></main><footer className="border-t border-[#e5e1dd] bg-white px-4 py-8 text-center text-xs text-[#888]" data-testid="contact-footer">Aangan Buildworks · Your land. Your home. Professionally built.</footer>
  </div>;
}
