import { ArrowLeft, MapPin } from "lucide-react";
import { Link } from "react-router-dom";

import { LeadFunnel } from "@/pages/Home";

const phone = import.meta.env.VITE_PUBLIC_PHONE as string | undefined;
const email = import.meta.env.VITE_PUBLIC_EMAIL as string | undefined;
const whatsapp = import.meta.env.VITE_PUBLIC_WHATSAPP as string | undefined;

export default function Contact() {
  return <div className="min-h-screen bg-[#fafafa] text-[#1a1a1a]" data-testid="contact-page">
    <header className="border-b border-[#e5e1dd] bg-white" data-testid="contact-header"><div className="mx-auto flex h-[72px] max-w-[1240px] items-center justify-between px-4 sm:px-8 lg:px-12"><Link to="/" className="flex items-center gap-3" data-testid="contact-back-home-link"><span className="grid size-9 place-items-center bg-[#1a1a1a] text-white"><span className="font-heading text-xl">A</span></span><span className="text-sm font-bold tracking-[0.08em]">AANGAN <span className="font-normal text-[#a38068]">BUILDWORKS</span></span></Link><Link to="/" className="flex items-center gap-2 text-xs font-bold text-[#666] hover:text-[#a38068]" data-testid="contact-return-link"><ArrowLeft size={15} /> Back to home</Link></div></header>
    <main><section className="bg-[#1f2423] px-4 py-20 text-white sm:px-8 lg:px-12 lg:py-28" data-testid="contact-hero-section"><div className="mx-auto max-w-[1240px]"><p className="mb-4 text-[11px] font-bold uppercase tracking-[0.22em] text-[#d0ad92]" data-testid="contact-eyebrow">Start with your land</p><h1 className="max-w-3xl text-5xl font-medium leading-[0.98] text-white sm:text-7xl" data-testid="contact-title">Let’s start with your land.</h1><p className="mt-6 max-w-lg text-base leading-7 text-white/65" data-testid="contact-subtitle">Tell us about the plot and home you’re planning. A home consultant will help you understand the next step.</p></div></section><section className="mx-auto grid max-w-[1240px] gap-12 px-4 py-16 sm:px-8 lg:grid-cols-[0.7fr_1.3fr] lg:px-12 lg:py-24" data-testid="contact-content"><div><p className="text-[11px] font-bold uppercase tracking-[0.22em] text-[#a38068]" data-testid="contact-details-eyebrow">Aangan Buildworks</p><h2 className="mt-4 text-3xl font-medium" data-testid="contact-details-title">A considered conversation, before a construction promise.</h2><p className="mt-5 text-sm leading-7 text-[#666]" data-testid="contact-details-copy">Send the brief on this page. A consultant replies from the company number when the plot is one we can take on. We do not publish a stand-in phone.</p><div className="mt-10 grid gap-5 text-sm">{phone && <a href={`tel:${phone}`} className="hover:text-[#a38068]" data-testid="contact-phone-link">{phone}</a>}{whatsapp && <a href={whatsapp} className="hover:text-[#a38068]" data-testid="contact-whatsapp-link">WhatsApp</a>}{email && <a href={`mailto:${email}`} className="hover:text-[#a38068]" data-testid="contact-email-link">{email}</a>}<span className="flex items-center gap-3 text-[#666]" data-testid="contact-location"><MapPin size={17} className="text-[#a38068]" /> Bihar, India · service availability confirmed by brief</span></div></div><LeadFunnel /></section></main><footer className="border-t border-[#e5e1dd] bg-white px-4 py-8 text-center text-xs text-[#888]" data-testid="contact-footer"><p>Aangan Buildworks · Your land. Your home. Professionally built.</p><Link to="/admin/login" className="mt-3 inline-block font-semibold text-[#666] hover:text-[#a38068]" data-testid="footer-admin-login-link">Admin login</Link></footer>
  </div>;
}
